ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER "c##app" IDENTIFIED BY netflix DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO "c##app";

-- CRIAR USUÁRIO AUDITOR --
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER "AUDITOR" IDENTIFIED BY aud123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- SEQUENCE DA TABELA DE AUDITORIA --
CREATE SEQUENCE AUDITOR.SQ_AUD NOCACHE;

-- TABELA DE AUDITORIA --
CREATE TABLE AUDITOR.AUDITORIA(
    aud_id INTEGER,
    aud_tabela VARCHAR(30),
    aud_linha_hist INTEGER,
        aud_data_hist DATE,
        aud_coluna VARCHAR(30),
        aud_valor_antigo VARCHAR(2000),
        aud_valor_novo VARCHAR(2000),
        aud_operacao CHAR(1),
        aud_data DATE,
        aud_usu_bd VARCHAR(30),
        aud_usu_so VARCHAR(200),
        CONSTRAINT PK_AUD PRIMARY KEY(aud_id)
);

-- TRIGGER DA SEQUENCE DA TABELA DE AUDITORIA --
CREATE TRIGGER AUDITOR.TG_SQ_AUD
BEFORE INSERT ON AUDITOR.AUDITORIA
FOR EACH ROW
BEGIN
    :NEW.aud_id := AUDITOR.SQ_AUD.NEXTVAL;
END;
/

-- PROCEDURE --
CREATE OR REPLACE PROCEDURE AUDITOR.PROC_INSERE
(
    PR_TABELA IN VARCHAR2,
    PR_LINHA_HIST IN NUMBER,
    PR_DATA_HIST IN DATE,
    PR_COLUNA IN VARCHAR2,
    PR_VALOR_ANTIGO IN VARCHAR2,
    PR_VALOR_NOVO IN VARCHAR2,
    PR_OPERACAO IN VARCHAR2,
    PR_DATA IN DATE,
    PR_USU_BD IN VARCHAR2,
    PR_USU_SO IN VARCHAR2
) AS
BEGIN
  INSERT INTO AUDITOR.AUDITORIA VALUES (null, PR_TABELA, PR_LINHA_HIST, PR_DATA_HIST, PR_COLUNA, PR_VALOR_ANTIGO,PR_VALOR_NOVO, PR_OPERACAO, PR_DATA, PR_USU_BD, PR_USU_SO);
END PROC_INSERE;


GRANT EXECUTE ON AUDITOR.PROC_INSERE TO "c##app";

CREATE USER "STAGE" IDENTIFIED BY stage123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO "STAGE";
--GRANT SELECT ON "NOME DA VIEW" TO "STAGE";--